services:
  ms-login:
    build: .
    container_name: ms-login
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres-ms-login
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms-login
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  default:
    name: local-network
